// General Requirements data for CostSummaryModule
// Each array below represents a section from the GC&GR Worksheet.xlsx, rows 68 and below
// All fields are mock/demo values and should match the GRLineItem interface

import { GRLineItem } from "./CostSummaryModule"

export const grTemporaryUtilities: GRLineItem[] = [
  {
    id: "temp_electrical_service",
    description: "Temp. Electrical Service",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by elect sub",
    rowType: "item",
  },
  {
    id: "temp_electrical_const",
    description: "Temp. Electrical - Const. Phase",
    quantity: 0,
    unit: "mos",
    unitCost: 8000,
    constCond: null,
    unitValue: 8000,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "In Hardcosts",
    rowType: "item",
  },
  {
    id: "temp_electrical_operate",
    description: "Temp. Electrical - Operate Phase",
    quantity: 0,
    unit: "mos",
    unitCost: 8000,
    constCond: null,
    unitValue: 8000,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "In Hardcosts",
    rowType: "item",
  },
  {
    id: "temp_wiring_lighting",
    description: "Temp. Wiring & Lighting",
    quantity: 0,
    unit: "sf",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by elect sub",
    rowType: "item",
  },
  {
    id: "temp_water_service",
    description: "Temporary Water - Service",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by plumb sub",
    rowType: "item",
  },
  {
    id: "temp_water",
    description: "Temporary Water",
    quantity: 0,
    unit: "mos",
    unitCost: 1000,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_toilets",
    description: "Temporary Toilets",
    quantity: 5,
    unit: "mos",
    unitCost: 1750,
    constCond: null,
    unitValue: null,
    generalReq: 8750,
    total: 8750,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_toilets_setup",
    description: "Temporary Toilet Set Up / Removal",
    quantity: 7,
    unit: "ea",
    unitCost: 93,
    constCond: null,
    unitValue: null,
    generalReq: 651,
    total: 651,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_washing_station",
    description: "Temporary Washing Station",
    quantity: 0,
    unit: "mos",
    unitCost: 407,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_washing_setup",
    description: "Temporary Washing Station Set Up / Removal",
    quantity: 0,
    unit: "ea",
    unitCost: 93,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_holding_tanks",
    description: "Temporary Holding Tanks",
    quantity: 5,
    unit: "mos",
    unitCost: 750,
    constCond: null,
    unitValue: null,
    generalReq: 3750,
    total: 3750,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_ventilation",
    description: "Temporary Ventilation",
    quantity: 0,
    unit: "h",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temp_cooling",
    description: "Temporary Cooling",
    quantity: 0,
    unit: "h",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
]

export const grCleaning: GRLineItem[] = [
  {
    id: "trash_removal_10yd",
    description: "Trash Removal - 10yd dumpsters",
    quantity: 0,
    unit: "wks",
    unitCost: 350,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "trash_removal_20yd",
    description: "Trash Removal - 20yd dumpsters",
    quantity: 0,
    unit: "wks",
    unitCost: 400,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "trash_removal_30yd",
    description: "Trash Removal - 30yd dumpsters",
    quantity: 0,
    unit: "wks",
    unitCost: 2500,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "trash_removal_offices",
    description: "Trash Removal - Field Offices",
    quantity: 0,
    unit: "wks",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "general_building_cleaning",
    description: "General Building Cleaning",
    quantity: 39,
    unit: "wks",
    unitCost: 520,
    constCond: null,
    unitValue: null,
    generalReq: 20354,
    total: 20354,
    percentTime: null,
    remarks: "In Hardcosts",
    rowType: "item",
  },
  {
    id: "final_building_clean",
    description: "Final Building Clean",
    quantity: 0,
    unit: "#",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "In Hardcosts",
    rowType: "item",
  },
]

export const grServices: GRLineItem[] = [
  {
    id: "cmp_schedule_setup",
    description: "CMP Schedule - Set Up",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "cpm_schedule_updates_standard",
    description: "CPM Schedule - Updates (Standard Reports)",
    quantity: 0,
    unit: "mos",
    unitCost: 1650,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "cpm_schedule_updates_bifurcated",
    description: "CPM Schedule - Updates (Bifurcated Reports)",
    quantity: 0,
    unit: "mos",
    unitCost: 300,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "progress_photos_ground",
    description: "Progress Photos Bldg. - Ground",
    quantity: 5,
    unit: "mos",
    unitCost: 50,
    constCond: null,
    unitValue: null,
    generalReq: 250,
    total: 250,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "progress_photos_aerial",
    description: "Progress Photos Bldg. - Aerial",
    quantity: 5,
    unit: "mos",
    unitCost: 100,
    constCond: null,
    unitValue: null,
    generalReq: 500,
    total: 500,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "video_existing_conditions",
    description: "Video - Existing Conditions",
    quantity: 0,
    unit: "ls",
    unitCost: 2500,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "video_owner_demo",
    description: "Video - Owner O&M Demo.",
    quantity: 0,
    unit: "ls",
    unitCost: 500,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "legal",
    description: "Legal",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
]

export const grDrawings: GRLineItem[] = [
  {
    id: "as_built_survey",
    description: "As Built Survey",
    quantity: 0,
    unit: "ls",
    unitCost: 1000,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "as_built_drawings",
    description: "As Built Drawings",
    quantity: 0,
    unit: "ls",
    unitCost: 500,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "plan_copy_expense",
    description: "Plan/Copy Expense",
    quantity: 1,
    unit: "ls",
    unitCost: 10000,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: 10000,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "postage_usps",
    description: "Postage - USPS",
    quantity: 5,
    unit: "mos",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: 375,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "postage_fedex",
    description: "Postage - Fed-X",
    quantity: 5,
    unit: "mos",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: 375,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
]

export const grTesting: GRLineItem[] = [
  {
    id: "concrete_testing",
    description: "Concrete Testing",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by owner",
    rowType: "item",
  },
  {
    id: "steel_testing",
    description: "Steel Testing",
    quantity: 0,
    unit: "ea",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by owner",
    rowType: "item",
  },
  {
    id: "special_inspectors",
    description: "Special Inspectors",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by owner",
    rowType: "item",
  },
]

export const grPermits: GRLineItem[] = [
  {
    id: "building_permits",
    description: "Building Permits",
    quantity: 5,
    unit: "ls",
    unitCost: 1000,
    constCond: null,
    unitValue: null,
    generalReq: 5000,
    total: 5000,
    percentTime: null,
    remarks: "Sub Trades Only",
    rowType: "item",
  },
  {
    id: "impact_fees",
    description: "Impact Fees",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by owner",
    rowType: "item",
  },
  {
    id: "trailer_permits",
    description: "Trailer Permits",
    quantity: 1,
    unit: "ea",
    unitCost: 500,
    constCond: null,
    unitValue: null,
    generalReq: 500,
    total: 500,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "off_site_permits",
    description: "Off Site Permits",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "by owner",
    rowType: "item",
  },
]

export const grTravel: GRLineItem[] = [
  {
    id: "airfare",
    description: "Airfare",
    quantity: 5,
    unit: "mos",
    unitCost: 2000,
    constCond: null,
    unitValue: null,
    generalReq: 10000,
    total: 10000,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "hotel",
    description: "Hotel",
    quantity: 5,
    unit: "mos",
    unitCost: 1000,
    constCond: null,
    unitValue: null,
    generalReq: 5000,
    total: 5000,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "per_diem",
    description: "Per Diem",
    quantity: 5,
    unit: "mos",
    unitCost: 850,
    constCond: null,
    unitValue: null,
    generalReq: 4250,
    total: 4250,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
]

export const grOther: GRLineItem[] = [
  {
    id: "project_sign",
    description: "Project Sign",
    quantity: 5,
    unit: "ea",
    unitCost: 1500,
    constCond: null,
    unitValue: null,
    generalReq: 7500,
    total: 7500,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "temporary_parking",
    description: "Temporary Parking",
    quantity: 0,
    unit: "ls",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
  {
    id: "legal_notices",
    description: "Legal Notices",
    quantity: 0,
    unit: "ea",
    unitCost: 0,
    constCond: null,
    unitValue: null,
    generalReq: null,
    total: null,
    percentTime: null,
    remarks: "",
    rowType: "item",
  },
]
