import type { ResponsibilityTask } from "@/types/responsibility"

export const mockRoles = [
  {
    key: "PM",
    name: "Project Manager",
    color: "#3B82F6",
    description: "Oversees project execution",
    enabled: true,
    category: "Management",
  },
  {
    key: "PE",
    name: "Project Engineer",
    color: "#10B981",
    description: "Handles technical project aspects",
    enabled: true,
    category: "Engineering",
  },
  {
    key: "SU",
    name: "Superintendent",
    color: "#F59E42",
    description: "Manages field operations",
    enabled: true,
    category: "Field",
  },
]

export const mockCategories = [
  {
    key: "safety",
    name: "Safety",
    description: "Safety management and compliance",
    color: "#EF4444",
    enabled: true,
  },
  {
    key: "quality",
    name: "Quality",
    description: "Quality assurance and control",
    color: "#6366F1",
    enabled: true,
  },
  {
    key: "schedule",
    name: "Schedule",
    description: "Schedule management",
    color: "#F59E42",
    enabled: true,
  },
]

export const mockResponsibilityTasks: ResponsibilityTask[] = [
  {
    id: "task-001",
    projectId: "401001",
    type: "team",
    category: "Contract Management",
    task: "Sign all contracts",
    page: "",
    article: "",
    responsible: "PX",
    assignments: {
      PX: "Primary",
      PM1: "Support",
      PM2: "None",
      PA: "None",
      QAC: "None",
      ProjAcct: "None",
      A: "None",
      C: "None",
      S: "None",
    },
    status: "active",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-06-01T10:00:00Z",
    annotations: [
      {
        id: "ann-001",
        user: "PM John Smith",
        timestamp: "2025-01-15T10:00:00Z",
        comment: "Contract signed and verified for compliance with project requirements.",
      },
    ],
  },
  {
    id: "task-002",
    projectId: "401001",
    type: "team",
    category: "Financial Management",
    task: "Review & Approve Subcontractor SOVs",
    page: "",
    article: "",
    responsible: "PM1",
    assignments: {
      PX: "Approve",
      PM1: "Primary",
      PM2: "None",
      PA: "None",
      QAC: "None",
      ProjAcct: "Support",
      A: "None",
      C: "None",
      S: "None",
    },
    status: "active",
    createdAt: "2025-01-15T10:30:00Z",
    updatedAt: "2025-06-01T10:30:00Z",
    annotations: [],
  },
  {
    id: "task-003",
    projectId: "401001",
    type: "prime-contract",
    category: "Contract Administration",
    task: "Review and approve change orders",
    page: "15",
    article: "3.2.1",
    responsible: "PM1",
    assignments: {
      PX: "Approve",
      PM1: "Primary",
      PM2: "None",
      PA: "Support",
      QAC: "None",
      ProjAcct: "Support",
      A: "None",
      C: "None",
      S: "None",
    },
    status: "active",
    createdAt: "2025-01-15T13:30:00Z",
    updatedAt: "2025-06-01T13:30:00Z",
    annotations: [],
  },
  {
    id: "task-004",
    projectId: "401001",
    type: "subcontract",
    category: "Electrical Systems",
    task: "Install electrical systems",
    page: "12",
    article: "E-2.1",
    responsible: "C",
    assignments: {
      PX: "None",
      PM1: "Approve",
      PM2: "None",
      PA: "None",
      QAC: "Support",
      ProjAcct: "None",
      A: "None",
      C: "Primary",
      S: "Support",
    },
    status: "pending",
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-06-01T10:00:00Z",
    annotations: [],
  },
  {
    id: "task-005",
    projectId: "401001",
    type: "team",
    category: "Quality Control",
    task: "Conduct Quality Inspections",
    page: "",
    article: "",
    responsible: "QAC",
    assignments: {
      PX: "None",
      PM1: "Support",
      PM2: "None",
      PA: "None",
      QAC: "Primary",
      ProjAcct: "None",
      A: "None",
      C: "Support",
      S: "None",
    },
    status: "completed",
    createdAt: "2025-01-15T11:30:00Z",
    updatedAt: "2025-06-01T11:30:00Z",
    annotations: [],
  },
]
